### ISSUE TITLE
Burp REST API plugin

### ISSUE THREAD

**Issue by Dr4s1l** [infobyte/faraday_plugins#10]
I'm aware of the burp extender and burp plugin using xml report. With version 2.0 of burp scanner, there is a basic REST API server. 
Is it possible to parse the output of this api to feed faraday ? 
More a enhancement request.

**Comment by aenima-x** [comment]
@Dr4s1l the the burp executor of faraday-agents.
[https://github.com/infobyte/faraday_agent_dispatcher](url)
Is uses that api rest

**Comment by Dr4s1l** [comment]
How to use with burp headless?
