### ISSUE TITLE
Missing dependency for Nuclei plugin

### ISSUE THREAD

**Issue by 303sec** [infobyte/faraday_plugins#17]
I installed faraday-plugins with pip via python 3.7, but it seems to be failing with nuclei. I added the packaging module and it now works, but I assume this means you need to add the dependency in the requirements. This is the output showing nuclei failing:

```
$ faraday-plugins list-plugins
Cant load plugin module: nuclei [No module named 'packaging']
Cant load plugin module: nuclei_legacy [No module named 'packaging']
Faraday Plugins v1.5.10
Available Plugins :
Name                                  ID               Command    Report
```

**Comment by aenima-x** [comment]
@303sec yes your are right.
We miss this because we dont use faraday-plugins as stand alone package.

We will fix it, thanls

**Comment by aenima-x** [comment]
Fixed
