### ISSUE TITLE
Add Defender for Endpoint Vulnerability as Source / Plugin

### ISSUE THREAD

**Issue by toellbe** [infobyte/faraday_plugins#23]
It would be great Microsoft Defender for Endpoint can used as data source of software vulnerabilities.

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines.md

**Comment by fedek** [comment]
Hey @toellbe 

Thanks for the recommendation, seems like a great idea! To make things easier do you have a sample file that you could share with us?

best!

**Comment by toellbe** [comment]
You will find an api response example following the link in my previous post:

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines.md

**Comment by Jannik1228** [comment]
@fedek Is there a update on this topic? If or when it is planned to implement this plugin?

**Comment by gmartinez95** [comment]
Hi @Jannik1228,  in the last release a Windows Defender's plugin was added. Feel free to try it and give us your feedback.
