### ISSUE TITLE
Add TFSec and Terrascan as Plugin

### ISSUE THREAD

**Issue by meerco** [infobyte/faraday_plugins#24]
Hi, i'm a Terraform developer and i would like to include in my pipeline TFSec and Terrascan. 
I would like to use faraday too as a vulnerability manager.
Is it possible to add these two plugins?
I will attach two .json output generated from TFSec and Terrascan.

[output_file_terrascan.txt](https://github.com/infobyte/faraday_plugins/files/12241566/output_file_terrascan.txt)
[output_file_tfsec.txt](https://github.com/infobyte/faraday_plugins/files/12241243/output_file_tfsec.txt)

**Comment by gmartinez95** [comment]
Hi @meerco,
I'm glad you chose us. 
I wll add this to the backlog and possibly it will be ready for the next release

**Comment by gmartinez95** [comment]
Hi @meerco 
The new plugins will in the next release, so I close these issue.
