### ISSUE TITLE
I can't send Nuclei's output to Faraday

### ISSUE THREAD

**Issue by Victor-Otsuga** [infobyte/faraday_plugins#25]
I tried to export the nuclei results in several files and none of them were accepted by Faraday, I tried uploading directly via the GUI and Faraday-cli, but the file was not accepted. I tried using Json, JSONL, XML, and several standard outputs from Nuclei, does anyone know how I can pass information from Nuclei to Faraday?
![image](https://github.com/infobyte/faraday_plugins/assets/105857027/95a57d0a-08fa-4bd9-8dd8-6407e7ec6198)

**Comment by gmartinez95** [comment]
Hi @Victor-Otsuga can you attach the report file that you are trying to upload?

**Comment by Victor-Otsuga** [comment]
> Hi @Victor-Otsuga can you attach the report file that you are trying to upload?

Of course, I got these files from the Nuclei output using -o output and -o output.json, I also tried the jsonl-export command in Nuclei (The file in the printout) but none of them were sent to Faraday.
(I tried to upload output.bin but github doesn't allow it)

[output (json).json](https://github.com/infobyte/faraday_plugins/files/13538008/output.json.json)

Let me know if there's anything I can do to resolve it

**Comment by Victor-Otsuga** [comment]
![image](https://github.com/infobyte/faraday_plugins/assets/105857027/78e197e1-6012-4f70-81aa-6654211086d0)
for some reason the Nuclei output is being recognized by the MBSA plugin instead of the Nuclei plugin

**Comment by thekibi** [comment]
By using nuclei -target <IP> -j -o <dir>/<filename>.json
A json file is generated that can be uploaded to Faraday. 
It would be great to know which file types of nuclei are allowed by Faraday. This can cost you lot of worktime for simple stuff. Fix your documentation!

**Comment by thekibi** [comment]
By using nuclei -target "ip" -j -o "outputfile.json"
A json file is generated that can be uploaded to Faraday.
It would be great to know which file types of nuclei are allowed by Faraday. This can cost you lot of worktime for simple stuff. Fix your documentation!
